parameters:
    default-width: 7;

services:
    powker4.game:
        class: Powker4Bundle\Api\Game
        arguments: []
#    powker4.example:
#        class: Powker4Bundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
