<?php

namespace Powker4Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceRepository extends EntityRepository
{
    public function retrievePiecesByColumn($column)
    {
        $pieces = $this->createQueryBuilder('p')
            ->select('pieces')
            ->from('piece', 'p')
            ->where('p.x = :column')
            ->orderBy('p.y', 'ASC')
        ;

        return $pieces->getQuery()->getResult();
    }
}
