<?php

namespace Powker4Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceRepository extends EntityRepository
{

    public function retrievePiecesByColumn($column, $grid)
    {
        $pieces = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.x = :column')
            ->andWhere('p.grid = :grid')
            ->orderBy('p.y', 'ASC')
            ->setParameter('column', $column)
            ->setParameter('grid', $grid)
        ;

        return $pieces->getQuery()->getResult();
    }

    public function findPiecesNumberByColor($gridId, $color)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
                SELECT count(p.id) FROM Powker4Bundle:Piece p
                WHERE p.grid = :gridId
                AND p.color = :color
            ')
            ->setParameter('gridId', $gridId)
            ->setParameter('color', $color)
        ;

        return $query->getResult();
    }
}
